### ISSUE TITLE
Combined issue. List All Enabled Apps and Control All Apps Scrobbling.

### ISSUE THREAD

**Issue by a93h** [simple-last-fm-scrobbler/sls#200]
This is a combination of two major issues I have been tracking which are variants of them same issue. Viewing and enabling/disabling scrobbling of all supported applications.

Example: may applications scrobble under "Android Music Player". Users should be able to control which applications scrobble under "Android Music Player". i.e. Podcasts.

Issues:
- #121 #123 #94 Users want all supported apps shown in Enabled Apps
- #130 #119 #88 Users want to control scrobbling apps

To discuss adding an ebook/podcast filter button/option, see #127

**Comment by konsept** [comment]
Hi @HumbleBeeBumbleBee, thanks for the update here.  I just wanted to add some clarity on the second issue noted -- *control scrobbling apps*

The issue in #127 is primarily as a intelligent noise filter for audio tracks which are not regarded as music (i.e. podcasts, ebooks, etc.) so that these do not get scrobbled while music tracks would.  Only reason for drawing this distinction is that many people will **use their favorite music player for both music and podcasts or ebooks**.  Therefore, simply disabling a particular app from scrobbling would not be sufficient.  If that is different than this requirement I'd suggest leaving #127 open.  Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
Thanks @konsept. For anybody who is worried about controlling scrobbling Podcasts via an
> intelligent noise filter
essentially detected when a podcast is being played and having a menu option to control scrobbling podcasts on/off
... please see #127 
Otherwise if you want to control by application please discuss here.

**Comment by HumbleBeeBumbleBee** [comment]
Example applications: [Podcast Addict](https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict), [Pocket Casts](https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts), [DoggCatcher](https://play.google.com/store/apps/details?id=com.snoggdoggler.android.applications.doggcatcher.v1_0), [Audible](https://play.google.com/store/apps/details?id=com.audible.application)

**Comment by HumbleBeeBumbleBee** [comment]
[DoggCatcher](https://play.google.com/store/apps/details?id=com.snoggdoggler.android.applications.doggcatcher.v1_0)
Reports that the app will have the ability to be disabled in the settings of SLS.
