### ISSUE TITLE
Spotify scrobbling twice

### ISSUE THREAD

**Issue by callumshell1** [simple-last-fm-scrobbler/sls#375]
Due to Spotify's wonderful feature of playing songs both on my desktop and on my phone at the same time whether I like it or not, tracks are being scrobbled twice. Once through Spotify's desktop program then again through SLS. Is there any way for SLS to detect when I'm actually listening to a song on my desktop and not on my phone to prevent this from happening? Right now I have to force close Spotify on my phone.

I don't use spotify's built in scrobbling on my phone due to the fact I'm often offline.

**Comment by eventheminions** [comment]
Can this issue please be addressed? SLS is my go-to scrobbler because it doesn't count double scrobbles when using a bluetooth speaker (like the official Last.fm app and Spotify do) and registers Chromecast scrobbles (unlike Spotify). 

However, the Spotify app DOES understand when my phone and my desktop are on the same WiFi network and scrobbles only once per song.  SLS cannot reconcile the two "signals" involved in Spotify Connect and submits two scrobbles at the same time. So no matter how I choose to scrobble, I still end up having to dig through the Last.fm site to delete doubles - bluetooth doubles for Spotify/official or Spotify Connect doubles for SLS! 

As I see it there are two solutions to this issue.
1. If SLS detects the exact same track in my Last.fm feed at the same time, it automatically deletes/does not submit one of those scobbles.
2. If SLS detects the use of Spotify Connect it does not submit scrobbles until the second device is disconnected.

In my opinion the first option is the cleaner and easier to implement of the two; I understand that Spotify may not share the inner workings of Connect with 3rd part developers. 

However, I imagine it is relatively straightforward to create a condition in which duplicates are automatically deleted. Having this occur AFTER a track is finished would probably eliminate the difficulty of reconciling two Now Playing statuses. It would simply be a case of regularly trawling through, say, the last ten tracks played and deleting any SLS scrobbles submitted for the SAME TRACK within the SAME MINUTE as others on the global scrobble list.

I hope this wouldn't be too tricky to implement, and I hope the developer reads these comments. SLS is a fantastic app with one flaw that sends me tediously scrolling through and deleting scrobbles just to make sure I have accurate listening stats. It's so close to being the perfect scrobbling app - please make this fix!

**Comment by wolflambert** [comment]
I've been looking for an Android scrobbler that does this for a while now. Spotify's integrated one has been pretty inconsistent (tracks don't get scrobbled quite often for whatever reason, and it doesn't appear to work offline), which caused me to switch to the official app, but now the double scrobbles are a problem.

If this is possible, I'd like to know! Following this thread.

**Comment by a93h** [comment]
Typically this is not our fault.
This usually mean that the official last.fm app, spotify, or some other program is also scrobbling the same time.
If it happens when the track is completed, then it's a problem.

**Comment by a93h** [comment]
Please try our newest fully signed apk. #479 <- the download is in the pre-release link.
Thanks,
Austin H.
