### ISSUE TITLE
Google Play Music not working?

### ISSUE THREAD

**Issue by RodrigoLeiteF** [simple-last-fm-scrobbler/sls#418]
I updated the app and now it doesn't recognize Google Play Music anymore. What do I do?

**Comment by lmsmarcel** [comment]
yeah, same problem but I installed the latest version available on Play Store, because I switch my phone, when stop working.
The last update continue not working.

**Comment by codysherman** [comment]
Chiming in to confirm that this issue still exists with latest OS, GPM, and SLS.

**Comment by G00fY2** [comment]
Fixes with #413

**Comment by XZaya** [comment]
Still got the Problem on S8+ (Android 8) :/

**Comment by jamgregory** [comment]
I'm experiencing a similar problem with Android 8.1 on the Nokia 7 Plus - neither this app nor the official Last.fm app can detect music being played and send my scrobbles to Last.fm

**Comment by bruzie** [comment]
GPM is not detected on Nokia 6.1 with Android 9.0

**Comment by a93-39a** [comment]
hello everyone,
I new comment format will be used for issue discussion.
Please, if you have the time and this is still an issue for you.
Use the following format

##### Preferred Feature format
  Request for Feature:
  Reason:
##### Preferred issue forma
  * Phone Model:
  * Android Version:
  * SLS Version: (5.3)
  * Music App(s) In Use: (ex. YT Music, Spotify)
  * Detected Music Apps(s): (List what apps SLS detected)
  * Enabled Options: (List what options you have enabled)
  * Issue: (Description of What The Issue Is)
  * Parameters: (ex. When, Where, Why & How The Issue Occurs)

**Comment by a93h** [comment]
#479  <- please try the newest signed debuggable android apk. Thanks.
