### ISSUE TITLE
Current displayed scrobble is" minutes" behind

### ISSUE THREAD

**Issue by MartinL0815** [simple-last-fm-scrobbler/sls#419]
Currently, no, since days sls is always some tracks behind the currently played track, no matter which played app is used (AmazonMusic, Rocket or BubblesUPNP).

To be more precise the notification is always much behind the current track. 

Can I provide more information to help analysing?

**Comment by MartinL0815** [comment]
Sorry, forgot some details. I'm on an older Medion LifeTab p831x with Android 5.0.2.

**Comment by MartinL0815** [comment]
Sorry, forgot some details. I'm on an older Medion LifeTab p831x with Android 5.0.2.

**Comment by r4taw2mg** [comment]
Same here. I am using Amazon Music. But tracks are scrobbled 10 to 20 minutes after I have played them. They do not queue up, it seems that the playing info needs that long to reach the app.

Scrobbler: 1.5.7
Z3 running 6.0.1

**Comment by MartinL0815** [comment]
@r4taw2mg done now on the new tablet with Android 7.1 and Amazon Music.
But after some tracks it's not about 10 to 20 minutes, about hours Friday in scrobbling into it stops seemingly.

**Comment by a93-39a** [comment]
##### Preferred Feature Format

  * Request for Feature: (Super cool awesome scrobble perfection)
  * Reason: (Life is music)

##### Preferred Issue Format

  * Phone Model: (Samsung S10)
  * Android Version: (9)
  * SLS Version: (5.3)
  * Music App(s) In Use: (ex. YT Music, Spotify)
  * Detected Music Apps(s): (List what apps SLS detected)
  * Enabled Options: (List what options you have enabled)
  * Issue: (Description of What The Issue Is)
  * Parameters: (ex. When, Where, Why & How The Issue Occurs)

**Comment by a93h** [comment]
Is the time on your phone and last.fm time-zones the same?
Last.fm is regional.
Are you using any kind of VPN or anything that would mess with your UTC?

**Comment by MartinL0815** [comment]
I use libre.fm, not last.fm.  what do I have to think of Herr?
Im not using any VPN connection.

**Comment by a93h** [comment]
Time on your phone is current for your region?

**Comment by a93h** [comment]
Hello again @MartinL0815 
Has this issue been resolved lately?
I will close this as stale for now.
