### ISSUE TITLE
Songs cache but won't scrobble suddenly

### ISSUE THREAD

**Issue by icantthinkofacreativeusername** [simple-last-fm-scrobbler/sls#450]
The app has been working perfectly until now but suddenly songs in the cache won't leave the app and go to last.fm. I'm using JetAudio Basic, but it's not an issue with that, because songs still cache without issue. Nothing has been updated, so it's very odd. The "Scrobble now" button doesn't seem to do anything when it's connected to the internet. When it isn't connected to the internet and I press that button, it says "limited network", so it's not like the button is magically disabled. I've also tried all the other "Scrobble now" buttons in the other various places, and I've gone through everything on the troubleshooting page. I currently have 195 songs cached, if that means anything, going back to the 13th of this month (September). This isn't directly related to the SLS issue, but I also noticed on my laptop after updating Ubuntu to 18.04 and reinstalling Clementine, I had to go into last.fm to allow Clementine to scrobble, which I don't think I had to do last time. Maybe the SLS issue I'm having is related to new last.fm updates somehow.

**Comment by rpgdev** [comment]
I can comfirm this.

**Comment by TiraelSedai** [comment]
I have the exact same issue right now.

@icantthinkofacreativeusername  how did you resolve it?

**Comment by a93-39a** [comment]
Can I ask what you send your music to?
Please click "View Scrobble Cache"
Should show the scrobble websites there. If it's just one website, it could be an issue with their servers.

**Comment by rpgdev** [comment]
I used to have the same problem and _I think_ it came down to a bug in my firewall app (afwall). Do you have a firewall installed? Please confirm that sls hasn't been blocked by it. If it doesn't seem to be blocked reapply the firewall rules once again. There was a bug with my firewall app that sometimes blocked one app randomly, and I think sls turned out to have been blocked as a result of this bug. I'm not quite sure since it's been a while but you can try to see if that's your case.

**Comment by a93-39a** [comment]
Often times it is either the Power Optimization Settings on the device or the Settings inside Simple Last.fm Scrobbler.

**Comment by TiraelSedai** [comment]
This could've been a bug in firewall, but it for sure is not the case. The reason is I have not installed anything between when it was working and not.

@a93-39a it couldn't been Power Optimization, please read the issue again.

So in my case I just clicked "Send data now", it still had big count on it, I verified that at least the end and the beginning of the cached list was scrobbled already to last.fm, I hit "clear cache" and the issue went away. I guess the issue in the first place was when SLS was trying to send data to last.fm, never got "200 OK" response back but the songs were indeed scrobbled and it stuck in "limbo" state where tracks are already in last.fm but SLS have no knowledge of that.

**Comment by a93-39a** [comment]
I will need to write some code for this correction.

0. None (the request passed all filters).
1. Filtered artist.
2. Filtered track.
3. Timestamp too far in the past. (<- most likely the issue)
4. Timestamp too far in the future.
5. Max daily scrobbles exceeded.

**Comment by a93-39a** [comment]
Do you guys think that would be a cool hack?
Falsifying track data to get them posted later?
I would need some math hacks to make sure you don't exceed your daily limit as you hack this "old data" problem.

**Comment by TiraelSedai** [comment]
I am not exactly sure that you're right and exactly my issue was that timestamp. Once again, I scrolled to the very end of the cached list and verified those songs were already scrobbled as played in that date in my last.fm account.

Falsifying track data is one option, dropping old songs from cache is the other, and I don't know if there is third.


In regards to the issue itself how we can properly mitigate it to the point, if you think issue is with old timestamp:
IIRC, SLS batches 50 songs and tries to upload them. Maybe try from newest to oldest? In that case at least we would always get rid of songs in cache that we CAN upload, and then somehow deal with "stale" songs in cache.

**Comment by a93-39a** [comment]
Yes, my thoughts exactly.
I can add text that notifies the use that the songs are past due.
Then maybe they can choose to mess up their information a bit with re-timestamped songs or destroy them.

**Comment by a93h** [comment]
The most recent version #479 pre-release should work.
Download the apk in the link.
I have yet to add old scrobbles fixes yet, but there was a lot of required work before I could even think about this.
