### ISSUE TITLE
New Simple Scrobbler not working

### ISSUE THREAD

**Issue by boiler-maker** [simple-last-fm-scrobbler/sls#526]
Ever since Simple Scrobbler for Android was updated it doesn't scrobble anymore.
Once the logo of the icon changed I went to see if there are any changes only to find out I was logged out.
There are 5 things you can login into: Last fm, Libre fm, ListenBrainz, GNU-FM Server and ListenBrainz Server.
I have no idea what the last four are so I just logged in into my LastFM account.
But not only that any music I play isn't scrobbled, my profile is completely empty..
Last scrobble submitted at: Never
Last now playing notification submitted at: Never
Scrobbles in local cache:0
Total tracks scrobbled:0
Total now playing notifications: 0

**Comment by a93h** [comment]
Can I ask what permissions you have enabled?
Can I ask what version of Android you are running?

**Comment by FLiNT-13-7** [comment]
Can't connect to last.fm server, too, but it looks like Simple Scrobbler isn't to blame, since foobar2000 (Win 10) can't submit scrobbles either atm.

Log reads:
[11:27:16] Audioscrobbler: Internal Server Error (500)
[11:27:16] Audioscrobbler: Waiting 60 seconds to retry.
[11:28:00] Audioscrobbler: Still awaiting handshake. Cache contains 2 tracks.
[11:28:19] Audioscrobbler: Internal Server Error (500)
[11:28:19] Audioscrobbler: Waiting 120 seconds to retry.

**Comment by FLiNT-13-7** [comment]
Update: Everything is back to normal.

**Comment by boiler-maker** [comment]
Nothing is back to normal for me. My Android version: 8.0.0
Sony Music Player and Winamp are two enabled apps. 
I'm only logged into my Last.fm account.

**Comment by a93h** [comment]
Hi boiler-maker,
Is there anyway I can help you debug this problem?
If it can detect the music apps, usually it detects the music playing.
Any chance you'd be willing to run a debug log capture command?

**Comment by boiler-maker** [comment]
You gonna have to help me with that cause I have no idea how to do that.
